### ISSUE TITLE
A bunch of errors, probably or not because I'm in 1.15.2?

### ISSUE THREAD

**Issue by SissyTrashQueen** [williambl/EssentialFeatures#75] opened 2020-03-23 05:01 UTC
- [x] ~~First off, the redstone rod sword and the redstone rod arrow have an error about the lightning, it isn't visually centered on the mob that was hit:
[Video to show what actually happens](https://imgur.com/a/VHupSPR)~~

 - [x] The portable jukebox keeps on playing music, even if you drop it.
[I don't know if this could even be fixed](https://imgur.com/a/w8rKMr7)

 - [x] There's a couple of rendering errors:
![2020-03-22_23 44 17](https://user-images.githubusercontent.com/55768134/77280405-f9d1cf00-6ca2-11ea-8eaa-cfd2d68881a5.png)
 - [x] Spike block:
![2020-03-23_01 02 58](https://user-images.githubusercontent.com/55768134/77280407-fa6a6580-6ca2-11ea-959e-3ac4cc005094.png)

 - [x] The door textures aren't transparent like their items textures show:
![2020-03-23_01 28 06](https://user-images.githubusercontent.com/55768134/77281611-39e68100-6ca6-11ea-8e2e-8eeae85d33bd.png)

 - [x] Also the floating items for the doors are bigger than their vanilla counterparts:
![2020-03-23_01 28 24](https://user-images.githubusercontent.com/55768134/77281638-4ec31480-6ca6-11ea-88ba-d2acd03c4c99.png)

 - [ ] Kind of off-topic, but a feature request to have a purpur and nether trapdoor.

 - [x] The blaze block burns not only mobs but also items, and doesn't seem to damage these in any way. This could be an enhancement request for the blaze block to burn items.
[Video to show what actually happens](https://imgur.com/a/fxUXT5h)

 - [x] The Observed block **eye texture** changes when you're looking at it, just so slightly, enough to bug me out.
![2020-03-22_22 59 26](https://user-images.githubusercontent.com/55768134/77280402-f8a0a200-6ca2-11ea-93fe-c4c5eccb1ef8.png)
![2020-03-22_22 59 29](https://user-images.githubusercontent.com/55768134/77280404-f9d1cf00-6ca2-11ea-9192-1b06ddc83bbc.png)

 - [x] I almost forgot, the Block Breaker breaks bedrock.

 - EssentialFeatures version: v3.1.0
 - Forge version: 31.1.26
 - Minecraft version: 1.15.2
 - Dedicated server, LAN game, or singleplayer: singleplayer
 - OS: Win10 Pro

**Comment by williambl** [comment] 2020-04-12 21:29
Thanks for the reports.

I'm afraid I can't reproduce the lightning error - is it possible you have another mod that modifies lightning installed?

**Comment by SissyTrashQueen** [comment] 2020-04-14 00:13
yes, that's actually not something caused by this mod. [Lightining "bug"](https://www.curseforge.com/minecraft/mc-mods/lightning-tweaks)
At first I thought this mod was abandoned, but hey cool to see all the work you've done! :)

**Comment by williambl** [comment] 2020-04-14 00:30
Glad to know you worked out what that was caused by.

I tend to work on this mod quite irregularly, due to various reasons. But not abandoned! :)

**Comment by williambl** [comment] 2020-04-15 18:13
All the bugs in this are now fixed, so I'm closing the issue. Thanks for reporting them. :)

The trapdoors feature request now lives in #76.

**Closed as completed by williambl** 2020-04-15 18:13 UTC
Labels: bug, enhancement, balance
